hosts:
  - http://localhost:8091
bucketName: bucketName
username: user
password: pass
logging:
  level: info
dcp:
  group:
    name: groupName
metadata:
  config:
    bucket: checkpoint-bucket-name
    scope: _default
    collection: _default
  type: couchbase
mongodb:
  connection:
    uri: "localhost:27017"
    database: exampleDB
  collectionMapping:
    _default: exampleCollection
  batch:
    tickerDuration: 10s
    sizeLimit: 1000
    byteSizeLimit: "10mb"
    concurrentRequest: 1
  connectionPool:
    maxPoolSize: 100
    minPoolSize: 5
    maxIdleTimeMS: 300000  # 5 minutes
  timeouts:
    connectTimeoutMS: 10000  # 10 seconds
    serverSelectionTimeoutMS: 30000  # 30 seconds
    socketTimeoutMS: 30000  # 30 seconds
  shardKeys:
    - "customer.id"