hosts:
  - couchbase:8091
bucketName: dcp-test
username: user
password: password
logging:
  level: info
dcp:
  group:
    name: groupName
metadata:
  config:
    bucket: dcp-test
    scope: _default
    collection: _default
  type: couchbase
mongodb:
  uri: "mongodb:27017"
  database: exampleDB
  collection: exampleCollection
  batchSizeLimit: 10
  batchTickerDuration: 10s
  concurrentRequest: 1
  shardKeys:
    - "customer.id"
  maxPoolSize: 100
  minPoolSize: 5
  maxIdleTimeMS: 300000  # 5 minutes
  connectTimeoutMS: 10000  # 10 seconds
  serverSelectionTimeoutMS: 30000  # 30 seconds
  socketTimeoutMS: 30000  # 30 seconds