name: Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.24'

      - name: Start containers
        run: docker compose up --wait --build --force-recreate --remove-orphans

      - name: Verify services are healthy
        run: |
          echo "Verifying Couchbase is accessible..."
          timeout 60 bash -c 'until curl -f http://user:123456@localhost:8091/pools/default/buckets/dcp-test; do echo "Waiting for Couchbase..."; sleep 5; done'
          echo "Verifying MongoDB is accessible..."
          timeout 60 bash -c 'until nc -z localhost 27017; do echo "Waiting for MongoDB..."; sleep 2; done'
          echo "All services are ready!"

      - name: Integration Test
        run: go test -v test/integration/integration_test.go
        env:
          INPUT_PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: docker compose down
